### PR TITLE
Allow interning objects with unknown size

### PR DESCRIPTION
**Pull request by ryzhyk**
Addresses issue #15.

- Add `T: ?Sized` bound to most impls.
- Added impls:
 ```
 impl<'a, T> From<&'a T> for ArcIntern<T>
 where
     T: Eq + Hash + Send + Sync + 'static + ?Sized,
     Arc<T>: From<&'a T>,
 ```
 and
 ```
 impl<T: Eq + Hash + Send + Sync + 'static + ?Sized> From<Box<T>> for ArcIntern<T>
 ```

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
Looks good to me

**Comment by jplatte** [comment]
Ohh actually this isn't *that* useful since `Arc`, in contrast to `Box`, is not `#[fundamental]` so `Arc<T>: From<&T>` can only be implemented by things in the standard library. I guess that is why serde's `Arc` / `Rc` support also uses `Box<T>: From<T>` as a bound.

Can this be done here as well, using `Box<T>: From<&T>` and going through the new / adjusted `Box` impl? I guess that will be a little less efficient unless it's optimized away, but will allow custom types.

**Comment by ryzhyk** [comment]
You can totally write  `impl From<&T> for Arc<T>` for any user-defined type: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d3926ee3231747b60b0af42d995de009.

Perhaps I misunderstand what the issue is.

**Comment by jplatte** [comment]
Ah sorry, I mixed things up. `TryFrom<&str> for Arc<TypeThatWrapsStr>` was the thing that didn't work where it does work for `Box`.

[ruma_identifiers::RoomId](https://docs.ruma.io/ruma_identifiers/struct.RoomId.html) is the kind of type that Jonathan wants / wanted to experiment with putting into `ArcIntern`. I'm pretty sure it should work now.

**Comment by ShadowJonathan** [comment]
I don't know about the `&'static T` bond, but other than that, this looks pretty good.

(Though I think https://github.com/ryzhyk/arc-interner/issues/12 would be related to such discussion)

**Comment by ryzhyk** [comment]
> I don't know about the &'static T bond

This is unfortunately required for [`TypeId`](https://doc.rust-lang.org/stable/std/any/struct.TypeId.html#impl) stuff to work.

**Comment by jplatte** [comment]
`'static` makes sense since you could otherwise have `ArcIntern<ThingThatReferencesLocalLifetime<'_>>` and extend that local lifetime through interning.

**Pull request merged**
